name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

env:
  python: 3.11

jobs:
  test:
    uses: ./.github/workflows/tests.yaml
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
      - name: Get version using setuptools
        id: get_version
        run: |
          echo ::set-output name=version::$(python setup.py --version)
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.get_version.outputs.version }}
          prerelease: ${{ contains(steps.get_version.outputs.version, '-')}}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
  publish:
    needs: release
    uses: ./.github/workflows/pypi.yaml

