name: Create Release

on:
  workflow_dispatch:

env:
  python: 3.11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
      - name: Get version using setuptools and save as variable use newer syntax
        id: get_version
        run: |
          echo ::set-output name=version::$(python setup.py --version)
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.get_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}


